# site settings
title: #Vórtice
subtitle: 
email: info@vorticepublishing.com
description: Publishing
baseurl: #"/vortice" # the subpath of your site, e.g. /blog
url: https://vorticepublishing.com
author: Vórtice
street_address: 
city: Lisboa (PT) 
state: 
zip_code:
country: Berlin (DE)
phone: +49 157 3326 2769

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
